services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    pull_policy: never
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - inception
    restart: always
  nginx:
    build: ./requirements/nginx
    image: nginx
    pull_policy: never
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    extra_hosts:
      - "kazokada.42.fr:127.0.0.1"
    restart: always
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    pull_policy: never
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/kazokada/data/db
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/kazokada/data/wp
      o : bind
      type : none

networks:
  inception:
    name: inception